version: "3.7"
services:
  database:
    image: mysql:5.7
    container_name: "database"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
  soccer-api:
    build: ./
    container_name: "soccer-api"
    ports:
      - 5000:5000
    environment:
      DATABASE_HOST: localhost
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: testdb
    depends_on:
      - database
