version: "3"

services:
  mysql:
    image: mysql:5.7.31
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: localhost
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: test
    depends_on:
      - mysql

volumes:
  db-data: {}
